### ISSUE TITLE
Use an annotation to register the template servlet

### ISSUE THREAD

**Issue by eallik** [earldouglas/xwp-template#2]
Now that working annotations support is included in the upcoming 0.7.0 release of xsbt-web-plugin, it could also be considered that the examples code in this repository be updated to leverage these changes. This would also make the README/code shorter. But I'm not sure about the implications.

**Comment by earldouglas** [comment]
Wow, somehow I missed this issue.  Pardon the delay.  Is annotation support still something you'd like to see in the documentation?

**Comment by eallik** [comment]
I think it's probably good to have but not something you should take on because of me — I've long moved away from Scala to Haskell nowadays, but thanks!
